"""empty message

Revision ID: 8f458fc347f9
Revises: d96dabdde01a
Create Date: 2020-03-23 23:48:40.513733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f458fc347f9'
down_revision = 'd96dabdde01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.ARRAY(sa.String(length=120)),
               existing_nullable=True,
               postgresql_using='genres::character varying(120)[]')
    op.alter_column('Venue', 'genres',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.ARRAY(sa.String(length=120)),
               existing_nullable=True,
               postgresql_using='genres::character varying(120)[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
               existing_type=sa.ARRAY(sa.String(length=120)),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('Artist', 'genres',
               existing_type=sa.ARRAY(sa.String(length=120)),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
